$schema = "./node_modules/wrangler/config-schema.json"
name = "shortlink-nav"
main = "./public/_worker.js"
compatibility_date = "2026-09-11"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "shortlink-nav"
database_id = "00000000-0000-0000-0000-000000000000"
