name = "st-nav"
pages_build_output_dir = "./public"
compatibility_date = "2026-09-11"

[[d1_databases]]
binding = "DB"
database_name = "st-nav"
database_id = "<your-d1-database-id>"
migrations_dir = "./migrations"

[observability]
enabled = true

[vars]
ST_NAV_VERSION = "1.0.3"
